export const ADMIN_GET_PARTICULIERS_REQUEST = "ADMIN_GET_PARTICULIERS_REQUEST";
export const ADMIN_GET_PARTICULIERS_SUCCESS = "ADMIN_GET_PARTICULIERS_SUCCESS";
export const ADMIN_GET_PARTICULIERS_FAIL = "ADMIN_GET_PARTICULIERS_FAIL";
export const ADMIN_GET_PARTICULIERS_RESET = "ADMIN_GET_PARTICULIERS_RESET";

export const ADMIN_GET_RDVS_REQUEST = "ADMIN_GET_RDVS_REQUEST";
export const ADMIN_GET_RDVS_SUCCESS = "ADMIN_GET_RDVS_SUCCESS";
export const ADMIN_GET_RDVS_FAIL = "ADMIN_GET_RDVS_FAIL";
export const ADMIN_GET_RDVS_RESET = "ADMIN_GET_RDVS_RESET";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_RESET = "ADMIN_LOGIN_RESET";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
