runtime: nodejs14
service: web-test
env_variables:
  serviceID: "VA28eae49b1cfebb3abe712e6638b42491"
  accountSID: "ACae80e0350ec7adb57562d50d4736e4d9"
  authToken: "0b9d9f6a641ee92ea7c5e2aa87bfabdd"
  TWILIO_ACCOUNT_SID: "ACae80e0350ec7adb57562d50d4736e4d9"
  TWILIO_API_KEY: "SKd3dfaf41fd981ef1000ee635bd2ed482"
  TWILIO_API_SECRET: "EmH6hbukYacjvVrljD9GiZS6I0JZJcXp"
  secret: "plantaxion"
  reCaptchaSecretKey: "6Lc7mVMcAAAAAD5GEQlneQedNjOS1le2JukFKMFR"
  host: "deft-idiom-312816:europe-west1:slyserve"
  user: "root"
  password: "slyserve@2021"
  database: "slyDB"
  timezone: "utc"
