export const ROLES = {
  PATIENT: "PATIENT",
  DOCTOR: "DOCTOR",
  PARAMEDICAL: "PARAMEDICAL",
  CLINIC_HOSPITAL: "CLINIC_HOSPITAL",
  AMBULANCE: "AMBULANCE",
  PHARMACY: "PHARMACY",
  LABORATORY: "LABORATORY",
  BLOOD_DONOR: "BLOOD_DONOR",
};
