export const AMBULANCE_SIGNUP_REQUEST = "AMBULANCE_SIGNUP_REQUEST";
export const AMBULANCE_SIGNUP_SUCCESS = "AMBULANCE_SIGNUP_SUCCESS";
export const AMBULANCE_SIGNUP_FAIL = "AMBULANCE_SIGNUP_FAIL";
export const AMBULANCE_SIGNUP_RESET = "AMBULANCE_SIGNUP_RESET";

export const AMBULANCE_CHECK_EXIST_REQUEST = "AMBULANCE_CHECK_EXIST_REQUEST";
export const AMBULANCE_CHECK_EXIST_SUCCESS = "AMBULANCE_CHECK_EXIST_SUCCESS";
export const AMBULANCE_CHECK_EXIST_FAIL = "AMBULANCE_CHECK_EXIST_FAIL";
export const AMBULANCE_CHECK_EXIST_RESET = "AMBULANCE_CHECK_EXIST_RESET";

export const AMBULANCE_LOGIN_REQUEST = "AMBULANCE_LOGIN_REQUEST";
export const AMBULANCE_LOGIN_SUCCESS = "AMBULANCE_LOGIN_SUCCESS";
export const AMBULANCE_LOGIN_FAIL = "AMBULANCE_LOGIN_FAIL";
export const AMBULANCE_LOGIN_RESET = "AMBULANCE_LOGIN_RESET";
export const AMBULANCE_LOGOUT = "AMBULANCE_LOGOUT";

export const AMBULANCE_SEARCH_REQUEST = "AMBULANCE_SEARCH_REQUEST";
export const AMBULANCE_SEARCH_SUCCESS = "AMBULANCE_SEARCH_SUCCESS";
export const AMBULANCE_SEARCH_FAIL = "AMBULANCE_SEARCH_FAIL";
export const AMBULANCE_SEARCH_RESET = "AMBULANCE_SEARCH_RESET";
