export const CLINIQUE_CHECK_EXIST_REQUEST = "CLINIQUE_CHECK_EXIST_REQUEST";
export const CLINIQUE_CHECK_EXIST_SUCCESS = "CLINIQUE_CHECK_EXIST_SUCCESS";
export const CLINIQUE_CHECK_EXIST_FAIL = "CLINIQUE_CHECK_EXIST_FAIL";
export const CLINIQUE_CHECK_EXIST_RESET = "CLINIQUE_CHECK_EXIST_RESET";

export const CLINIQUE_LOGIN_REQUEST = "CLINIQUE_LOGIN_REQUEST";
export const CLINIQUE_LOGIN_SUCCESS = "CLINIQUE_LOGIN_SUCCESS";
export const CLINIQUE_LOGIN_FAIL = "CLINIQUE_LOGIN_FAIL";
export const CLINIQUE_LOGIN_RESET = "CLINIQUE_LOGIN_RESET";
export const CLINIQUE_LOGOUT = "CLINIQUE_LOGOUT";

export const CLINIQUE_SEARCH_REQUEST = "CLINIQUE_SEARCH_REQUEST";
export const CLINIQUE_SEARCH_SUCCESS = "CLINIQUE_SEARCH_SUCCESS";
export const CLINIQUE_SEARCH_FAIL = "CLINIQUE_SEARCH_FAIL";
export const CLINIQUE_SEARCH_RESET = "CLINIQUE_SEARCH_RESET";
