export const LABORATOIRE_CHECK_EXIST_REQUEST = "LABORATOIRE_CHECK_EXIST_REQUEST";
export const LABORATOIRE_CHECK_EXIST_SUCCESS = "LABORATOIRE_CHECK_EXIST_SUCCESS";
export const LABORATOIRE_CHECK_EXIST_FAIL = "LABORATOIRE_CHECK_EXIST_FAIL";
export const LABORATOIRE_CHECK_EXIST_RESET = "LABORATOIRE_CHECK_EXIST_RESET";

export const LABORATOIRE_LOGIN_REQUEST = "LABORATOIRE_LOGIN_REQUEST";
export const LABORATOIRE_LOGIN_SUCCESS = "LABORATOIRE_LOGIN_SUCCESS";
export const LABORATOIRE_LOGIN_FAIL = "LABORATOIRE_LOGIN_FAIL";
export const LABORATOIRE_LOGIN_RESET = "LABORATOIRE_LOGIN_RESET";
export const LABORATOIRE_LOGOUT = "LABORATOIRE_LOGOUT";

export const LABORATOIRE_SEARCH_REQUEST = "LABORATOIRE_SEARCH_REQUEST";
export const LABORATOIRE_SEARCH_SUCCESS = "LABORATOIRE_SEARCH_SUCCESS";
export const LABORATOIRE_SEARCH_FAIL = "LABORATOIRE_SEARCH_FAIL";
export const LABORATOIRE_SEARCH_RESET = "LABORATOIRE_SEARCH_RESET";
