export const PHARMACIE_CHECK_EXIST_REQUEST = "PHARMACIE_CHECK_EXIST_REQUEST";
export const PHARMACIE_CHECK_EXIST_SUCCESS = "PHARMACIE_CHECK_EXIST_SUCCESS";
export const PHARMACIE_CHECK_EXIST_FAIL = "PHARMACIE_CHECK_EXIST_FAIL";
export const PHARMACIE_CHECK_EXIST_RESET = "PHARMACIE_CHECK_EXIST_RESET";

export const PHARMACIE_LOGIN_REQUEST = "PHARMACIE_LOGIN_REQUEST";
export const PHARMACIE_LOGIN_SUCCESS = "PHARMACIE_LOGIN_SUCCESS";
export const PHARMACIE_LOGIN_FAIL = "PHARMACIE_LOGIN_FAIL";
export const PHARMACIE_LOGIN_RESET = "PHARMACIE_LOGIN_RESET";
export const PHARMACIE_LOGOUT = "PHARMACIE_LOGOUT";

export const PHARMACIE_SEARCH_REQUEST = "PHARMACIE_SEARCH_REQUEST";
export const PHARMACIE_SEARCH_SUCCESS = "PHARMACIE_SEARCH_SUCCESS";
export const PHARMACIE_SEARCH_FAIL = "PHARMACIE_SEARCH_FAIL";
export const PHARMACIE_SEARCH_RESET = "PHARMACIE_SEARCH_RESET";
