export const GET_SPECIALITES_REQUEST = "GET_SPECIALITES_REQUEST";
export const GET_SPECIALITES_SUCCESS = "GET_SPECIALITES_SUCCESS";
export const GET_SPECIALITES_FAIL = "GET_SPECIALITES_FAIL";

export const PROFESSIONNEL_SIGNUP_REQUEST = "PROFESSIONNEL_SIGNUP_REQUEST";
export const PROFESSIONNEL_SIGNUP_SUCCESS = "PROFESSIONNEL_SIGNUP_SUCCESS";
export const PROFESSIONNEL_SIGNUP_FAIL = "PROFESSIONNEL_SIGNUP_FAIL";

export const SAVE_PROFESSIONNEL = "SAVE_PROFESSIONNEL";

export const CHECK_PROFESSIONNEL_EXIST_REQUEST =
  "CHECK_PROFESSIONNEL_EXIST_REQUEST";
export const CHECK_PROFESSIONNEL_EXIST_SUCCESS =
  "CHECK_PROFESSIONNEL_EXIST_SUCCESS";
export const CHECK_PROFESSIONNEL_EXIST_FAIL = "CHECK_PROFESSIONNEL_EXIST_FAIL";

export const SEARCH_MEDECIN_REQUEST = "SEARCH_MEDECIN_REQUEST";
export const SEARCH_MEDECIN_SUCCESS = "SEARCH_MEDECIN_SUCCESS";
export const SEARCH_MEDECIN_FAIL = "SEARCH_MEDECIN_FAIL";

export const GET_MEDECIN_INFO_REQUEST = "GET_MEDECIN_INFO_REQUEST";
export const GET_MEDECIN_INFO_SUCCESS = "GET_MEDECIN_INFO_SUCCESS";
export const GET_MEDECIN_INFO_FAIL = "GET_MEDECIN_INFO_FAIL";
export const GET_MEDECIN_INFO_RESET = "GET_MEDECIN_INFO_RESET";

export const RESET_USER_CHECK = "RESET_USER_CHECK";

export const PROFESSIONNEL_REGISTER_RESET = "PROFESSIONNEL_REGISTER_RESET";
export const SAVE_PRO_RESET = "SAVE_PRO_RESET";

export const MEDECIN_LOGIN_REQUEST = "MEDECIN_LOGIN_REQUEST";
export const MEDECIN_LOGIN_SUCCESS = "MEDECIN_LOGIN_SUCCESS";
export const MEDECIN_LOGIN_FAIL = "MEDECIN_LOGIN_FAIL";

export const MEDECIN_LOGOUT = "MEDECIN_LOGOUT";
export const MEDECIN_LOGIN_RESET = "MEDECIN_LOGIN_RESET";

export const MEDECIN_GET_RDV_REQUEST = "MEDECIN_GET_RDV_REQUEST";
export const MEDECIN_GET_RDV_SUCCESS = "MEDECIN_GET_RDV_SUCCESS";
export const MEDECIN_GET_RDV_FAIL = "MEDECIN_GET_RDV_FAIL";

export const MEDECIN_GET_RDV_BYID_REQUEST = "MEDECIN_GET_RDV_BYID_REQUEST";
export const MEDECIN_GET_RDV_BYID_SUCCESS = "MEDECIN_GET_RDV_BYID_SUCCESS";
export const MEDECIN_GET_RDV_BYID_FAIL = "MEDECIN_GET_RDV_BYID_FAIL";
export const MEDECIN_GET_RDV_BYID_RESET = "MEDECIN_GET_RDV_BYID_RESET";

export const MEDECIN_UPDATE_RDV_REQUEST = "MEDECIN_UPDATE_RDV_REQUEST";
export const MEDECIN_UPDATE_RDV_SUCCESS = "MEDECIN_UPDATE_RDV_SUCCESS";
export const MEDECIN_UPDATE_RDV_FAIL = "MEDECIN_UPDATE_RDV_FAIL";
export const MEDECIN_UPDATE_RDV_RESET = "MEDECIN_UPDATE_RDV_RESET";

export const MEDECIN_ADD_ORDONNANCE_REQUEST = "MEDECIN_ADD_ORDONNANCE_REQUEST";
export const MEDECIN_ADD_ORDONNANCE_SUCCESS = "MEDECIN_ADD_ORDONNANCE_SUCCESS";
export const MEDECIN_ADD_ORDONNANCE_FAIL = "MEDECIN_ADD_ORDONNANCE_FAIL";
export const MEDECIN_ADD_ORDONNANCE_RESET = "MEDECIN_ADD_ORDONNANCE_RESET";

export const MEDECIN_ADD_COMPTERENDU_REQUEST =
  "MEDECIN_ADD_COMPTERENDU_REQUEST";
export const MEDECIN_ADD_COMPTERENDU_SUCCESS =
  "MEDECIN_ADD_COMPTERENDU_SUCCESS";
export const MEDECIN_ADD_COMPTERENDU_FAIL = "MEDECIN_ADD_COMPTERENDU_FAIL";
export const MEDECIN_ADD_COMPTERENDU_RESET = "MEDECIN_ADD_COMPTERENDU_RESET";

export const MEDECIN_UPDATE_PROFILE_REQUEST = "MEDECIN_UPDATE_PROFILE_REQUEST";
export const MEDECIN_UPDATE_PROFILE_SUCCESS = "MEDECIN_UPDATE_PROFILE_SUCCESS";
export const MEDECIN_UPDATE_PROFILE_FAIL = "MEDECIN_UPDATE_PROFILE_FAIL";
export const MEDECIN_UPDATE_PROFILE_RESET = "MEDECIN_UPDATE_PROFILE_RESET";

export const MEDECIN_GET_HORAIRES_REQUEST = "MEDECIN_GET_HORAIRES_REQUEST";
export const MEDECIN_GET_HORAIRES_SUCCESS = "MEDECIN_GET_HORAIRES_SUCCESS";
export const MEDECIN_GET_HORAIRES_FAIL = "MEDECIN_GET_HORAIRES_FAIL";
export const MEDECIN_GET_HORAIRES_RESET = "MEDECIN_GET_HORAIRES_RESET";

export const MEDECIN_GET_PATIENTS_REQUEST = "MEDECIN_GET_PATIENTS_REQUEST";
export const MEDECIN_GET_PATIENTS_SUCCESS = "MEDECIN_GET_PATIENTS_SUCCESS";
export const MEDECIN_GET_PATIENTS_FAIL = "MEDECIN_GET_PATIENTS_FAIL";

export const MEDECIN_ABONNER_REQUEST = "MEDECIN_ABONNER_REQUEST";
export const MEDECIN_ABONNER_SUCCESS = "MEDECIN_ABONNER_SUCCESS";
export const MEDECIN_ABONNER_FAIL = "MEDECIN_ABONNER_FAIL";
export const MEDECIN_ABONNER_RESET = "MEDECIN_ABONNER_RESET";

export const MEDECIN_ADD_PATIENT_REQUEST = "MEDECIN_ADD_PATIENT_REQUEST";
export const MEDECIN_ADD_PATIENT_SUCCESS = "MEDECIN_ADD_PATIENT_SUCCESS";
export const MEDECIN_ADD_PATIENT_FAIL = "MEDECIN_ADD_PATIENT_FAIL";
export const MEDECIN_ADD_PATIENT_RESET = "MEDECIN_ADD_PATIENT_RESET";

export const MEDECIN_GET_ABONNEMENT_REQUEST = "MEDECIN_GET_ABONNEMENT_REQUEST";
export const MEDECIN_GET_ABONNEMENT_SUCCESS = "MEDECIN_GET_ABONNEMENT_SUCCESS";
export const MEDECIN_GET_ABONNEMENT_FAIL = "MEDECIN_GET_ABONNEMENT_FAIL";

//

export const SEARCH_PARAMEDICAL_REQUEST = "SEARCH_PARAMEDICAL_REQUEST";
export const SEARCH_PARAMEDICAL_SUCCESS = "SEARCH_PARAMEDICAL_SUCCESS";
export const SEARCH_PARAMEDICAL_FAIL = "SEARCH_PARAMEDICAL_FAIL";

export const GET_PARAMEDICAL_INFO_REQUEST = "GET_PARAMEDICAL_INFO_REQUEST";
export const GET_PARAMEDICAL_INFO_SUCCESS = "GET_PARAMEDICAL_INFO_SUCCESS";
export const GET_PARAMEDICAL_INFO_FAIL = "GET_PARAMEDICAL_INFO_FAIL";
export const GET_PARAMEDICAL_INFO_RESET = "GET_PARAMEDICAL_INFO_RESET";

export const PARAMEDICAL_LOGIN_REQUEST = "PARAMEDICAL_LOGIN_REQUEST";
export const PARAMEDICAL_LOGIN_SUCCESS = "PARAMEDICAL_LOGIN_SUCCESS";
export const PARAMEDICAL_LOGIN_FAIL = "PARAMEDICAL_LOGIN_FAIL";

export const PARAMEDICAL_LOGOUT = "PARAMEDICAL_LOGOUT";
export const PARAMEDICAL_LOGIN_RESET = "PARAMEDICAL_LOGIN_RESET";

export const PARAMEDICAL_GET_RDV_REQUEST = "PARAMEDICAL_GET_RDV_REQUEST";
export const PARAMEDICAL_GET_RDV_SUCCESS = "PARAMEDICAL_GET_RDV_SUCCESS";
export const PARAMEDICAL_GET_RDV_FAIL = "PARAMEDICAL_GET_RDV_FAIL";

export const PARAMEDICAL_GET_RDV_BYID_REQUEST = "PARAMEDICAL_GET_RDV_BYID_REQUEST";
export const PARAMEDICAL_GET_RDV_BYID_SUCCESS = "PARAMEDICAL_GET_RDV_BYID_SUCCESS";
export const PARAMEDICAL_GET_RDV_BYID_FAIL = "PARAMEDICAL_GET_RDV_BYID_FAIL";
export const PARAMEDICAL_GET_RDV_BYID_RESET = "PARAMEDICAL_GET_RDV_BYID_RESET";

export const PARAMEDICAL_UPDATE_RDV_REQUEST = "PARAMEDICAL_UPDATE_RDV_REQUEST";
export const PARAMEDICAL_UPDATE_RDV_SUCCESS = "PARAMEDICAL_UPDATE_RDV_SUCCESS";
export const PARAMEDICAL_UPDATE_RDV_FAIL = "PARAMEDICAL_UPDATE_RDV_FAIL";
export const PARAMEDICAL_UPDATE_RDV_RESET = "PARAMEDICAL_UPDATE_RDV_RESET";

export const PARAMEDICAL_ADD_ORDONNANCE_REQUEST = "PARAMEDICAL_ADD_ORDONNANCE_REQUEST";
export const PARAMEDICAL_ADD_ORDONNANCE_SUCCESS = "PARAMEDICAL_ADD_ORDONNANCE_SUCCESS";
export const PARAMEDICAL_ADD_ORDONNANCE_FAIL = "PARAMEDICAL_ADD_ORDONNANCE_FAIL";
export const PARAMEDICAL_ADD_ORDONNANCE_RESET = "PARAMEDICAL_ADD_ORDONNANCE_RESET";

export const PARAMEDICAL_ADD_COMPTERENDU_REQUEST =
  "PARAMEDICAL_ADD_COMPTERENDU_REQUEST";
export const PARAMEDICAL_ADD_COMPTERENDU_SUCCESS =
  "PARAMEDICAL_ADD_COMPTERENDU_SUCCESS";
export const PARAMEDICAL_ADD_COMPTERENDU_FAIL = "PARAMEDICAL_ADD_COMPTERENDU_FAIL";
export const PARAMEDICAL_ADD_COMPTERENDU_RESET = "PARAMEDICAL_ADD_COMPTERENDU_RESET";

export const PARAMEDICAL_UPDATE_PROFILE_REQUEST = "PARAMEDICAL_UPDATE_PROFILE_REQUEST";
export const PARAMEDICAL_UPDATE_PROFILE_SUCCESS = "PARAMEDICAL_UPDATE_PROFILE_SUCCESS";
export const PARAMEDICAL_UPDATE_PROFILE_FAIL = "PARAMEDICAL_UPDATE_PROFILE_FAIL";
export const PARAMEDICAL_UPDATE_PROFILE_RESET = "PARAMEDICAL_UPDATE_PROFILE_RESET";

export const PARAMEDICAL_GET_HORAIRES_REQUEST = "PARAMEDICAL_GET_HORAIRES_REQUEST";
export const PARAMEDICAL_GET_HORAIRES_SUCCESS = "PARAMEDICAL_GET_HORAIRES_SUCCESS";
export const PARAMEDICAL_GET_HORAIRES_FAIL = "PARAMEDICAL_GET_HORAIRES_FAIL";
export const PARAMEDICAL_GET_HORAIRES_RESET = "PARAMEDICAL_GET_HORAIRES_RESET";

export const PARAMEDICAL_GET_PATIENTS_REQUEST = "PARAMEDICAL_GET_PATIENTS_REQUEST";
export const PARAMEDICAL_GET_PATIENTS_SUCCESS = "PARAMEDICAL_GET_PATIENTS_SUCCESS";
export const PARAMEDICAL_GET_PATIENTS_FAIL = "PARAMEDICAL_GET_PATIENTS_FAIL";

export const PARAMEDICAL_ABONNER_REQUEST = "PARAMEDICAL_ABONNER_REQUEST";
export const PARAMEDICAL_ABONNER_SUCCESS = "PARAMEDICAL_ABONNER_SUCCESS";
export const PARAMEDICAL_ABONNER_FAIL = "PARAMEDICAL_ABONNER_FAIL";
export const PARAMEDICAL_ABONNER_RESET = "PARAMEDICAL_ABONNER_RESET";

export const PARAMEDICAL_ADD_PATIENT_REQUEST = "PARAMEDICAL_ADD_PATIENT_REQUEST";
export const PARAMEDICAL_ADD_PATIENT_SUCCESS = "PARAMEDICAL_ADD_PATIENT_SUCCESS";
export const PARAMEDICAL_ADD_PATIENT_FAIL = "PARAMEDICAL_ADD_PATIENT_FAIL";
export const PARAMEDICAL_ADD_PATIENT_RESET = "PARAMEDICAL_ADD_PATIENT_RESET";

export const PARAMEDICAL_GET_ABONNEMENT_REQUEST = "PARAMEDICAL_GET_ABONNEMENT_REQUEST";
export const PARAMEDICAL_GET_ABONNEMENT_SUCCESS = "PARAMEDICAL_GET_ABONNEMENT_SUCCESS";
export const PARAMEDICAL_GET_ABONNEMENT_FAIL = "PARAMEDICAL_GET_ABONNEMENT_FAIL";