export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const GET_WILAYA_REQUEST = "GET_WILAYA_REQUEST";
export const GET_WILAYA_SUCCESS = "GET_WILAYA_SUCCESS";
export const GET_WILAYA_FAIL = "GET_WILAYA_FAIL";

export const GET_COMMUNES_REQUEST = "GET_COMMUNES_REQUEST";
export const GET_COMMUNES_SUCCESS = "GET_COMMUNES_SUCCESS";
export const GET_COMMUNES_FAIL = "GET_COMMUNES_FAIL";

export const SEND_CODE_REQUEST = "SEND_CODE_REQUEST";
export const SEND_CODE_SUCCESS = "SEND_CODE_SUCCESS";
export const SEND_CODE_FAIL = "SEND_CODE_FAIL";

export const VERIFY_CODE_REQUEST = "VERIFY_CODE_REQUEST";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_FAIL = "VERIFY_CODE_FAIL";

export const SAVE_USER = "SAVE_USER";

export const GET_VIDEO_TOKEN_REQUEST = "GET_VIDEO_TOKEN_REQUEST";
export const GET_VIDEO_TOKEN_SUCCESS = "GET_VIDEO_TOKEN_SUCCESS";
export const GET_VIDEO_TOKEN_FAIL = "GET_VIDEO_TOKEN_FAIL";
export const GET_VIDEO_TOKEN_RESET = "GET_VIDEO_TOKEN_RESET";

export const SAVE_VIDEO_PARAMS = "SAVE_VIDEO_PARAMS";

export const CHECK_PARTICULIER_EXIST_REQUEST =
  "CHECK_PARTICULIER_EXIST_REQUEST";
export const CHECK_PARTICULIER_EXIST_SUCCESS =
  "CHECK_PARTICULIER_EXIST_SUCCESS";
export const CHECK_PARTICULIER_EXIST_FAIL = "CHECK_PARTICULIER_EXIST_FAIL";

export const PARTICULIER_LOGIN_REQUEST = "PARTICULIER_LOGIN_REQUEST";
export const PARTICULIER_LOGIN_SUCCESS = "PARTICULIER_LOGIN_SUCCESS";
export const PARTICULIER_LOGIN_FAIL = "PARTICULIER_LOGIN_FAIL";
export const PARTICULIER_LOGOUT = "PARTICULIER_LOGOUT";

export const ADD_RDV_REQUEST = "ADD_RDV_REQUEST";
export const ADD_RDV_SUCCESS = "ADD_RDV_SUCCESS";
export const ADD_RDV_FAIL = "ADD_RDV_FAIL";
export const ADD_RDV_RESET = "ADD_RDV_RESET";

export const PARTICULIER_GET_RDV_REQUEST = "PARTICULIER_GET_RDV_REQUEST";
export const PARTICULIER_GET_RDV_SUCCESS = "PARTICULIER_GET_RDV_SUCCESS";
export const PARTICULIER_GET_RDV_FAIL = "PARTICULIER_GET_RDV_FAIL";

export const PARTICULIER_GET_COMPTES_RENDUS_REQUEST =
  "PARTICULIER_GET_COMPTES_RENDUS_REQUEST";
export const PARTICULIER_GET_COMPTES_RENDUS_SUCCESS =
  "PARTICULIER_GET_COMPTES_RENDUS_SUCCESS";
export const PARTICULIER_GET_COMPTES_RENDUS_FAIL =
  "PARTICULIER_GET_COMPTES_RENDUS_FAIL";

export const PARTICULIER_GET_ORDONNAnCE_BYID_REQUEST =
  "PARTICULIER_GET_ORDONNAnCE_BYID_REQUEST";
export const PARTICULIER_GET_ORDONNAnCE_BYID_SUCCESS =
  "PARTICULIER_GET_ORDONNAnCE_BYID_SUCCESS";
export const PARTICULIER_GET_ORDONNAnCE_BYID_FAIL =
  "PARTICULIER_GET_ORDONNAnCE_BYID_FAIL";

export const PARTICULIER_DELETE_ORDONNANCE_REQUEST =
  "PARTICULIER_DELETE_ORDONNANCE_REQUEST";
export const PARTICULIER_DELETE_ORDONNANCE_SUCCESS =
  "PARTICULIER_DELETE_ORDONNANCE_SUCCESS";
export const PARTICULIER_DELETE_ORDONNANCE_FAIL =
  "PARTICULIER_DELETE_ORDONNANCE_FAIL";
export const PARTICULIER_DELETE_ORDONNANCE_RESET =
  "PARTICULIER_DELETE_ORDONNANCE_RESET";

export const PARTICULIER_GET_PROFILE_REQUEST =
  "PARTICULIER_GET_PROFILE_REQUEST";
export const PARTICULIER_GET_PROFILE_SUCCESS =
  "PARTICULIER_GET_PROFILE_SUCCESS";
export const PARTICULIER_GET_PROFILE_FAIL = "PARTICULIER_GET_PROFILE_FAIL";

export const PARTICULIER_UPDATE_PROFILE_REQUEST =
  "PARTICULIER_UPDATE_PROFILE_REQUEST";
export const PARTICULIER_UPDATE_PROFILE_SUCCESS =
  "PARTICULIER_UPDATE_PROFILE_SUCCESS";
export const PARTICULIER_UPDATE_PROFILE_FAIL =
  "PARTICULIER_UPDATE_PROFILE_FAIL";
export const PARTICULIER_UPDATE_PROFILE_RESET =
  "PARTICULIER_UPDATE_PROFILE_RESET";

export const PARTICULIER_ADD_PROCHE_REQUEST = "PARTICULIER_ADD_PROCHE_REQUEST";
export const PARTICULIER_ADD_PROCHE_SUCCESS = "PARTICULIER_ADD_PROCHE_SUCCESS";
export const PARTICULIER_ADD_PROCHE_FAIL = "PARTICULIER_ADD_PROCHE_FAIL";
export const PARTICULIER_ADD_PROCHE_RESET = "PARTICULIER_ADD_PROCHE_RESET";

export const PARTICULIER_GET_PROCHES_REQUEST =
  "PARTICULIER_GET_PROCHES_REQUEST";
export const PARTICULIER_GET_PROCHES_SUCCESS =
  "PARTICULIER_GET_PROCHES_SUCCESS";
export const PARTICULIER_GET_PROCHES_FAIL = "PARTICULIER_GET_PROCHES_FAIL";

export const PARTICULIER_UPDATE_RDV_REQUEST = "PARTICULIER_UPDATE_RDV_REQUEST";
export const PARTICULIER_UPDATE_RDV_SUCCESS = "PARTICULIER_UPDATE_RDV_SUCCESS";
export const PARTICULIER_UPDATE_RDV_FAIL = "PARTICULIER_UPDATE_RDV_FAIL";
export const PARTICULIER_UPDATE_RDV_RESET = "PARTICULIER_UPDATE_RDV_RESET";

export const PARTICULIER_ANNULER_RDV_REQUEST =
  "PARTICULIER_ANNULER_RDV_REQUEST";
export const PARTICULIER_ANNULER_RDV_SUCCESS =
  "PARTICULIER_ANNULER_RDV_SUCCESS";
export const PARTICULIER_ANNULER_RDV_FAIL = "PARTICULIER_ANNULER_RDV_FAIL";
export const PARTICULIER_ANNULER_RDV_RESET = "PARTICULIER_ANNULER_RDV_RESET";

export const PARTICULIER_GET_ORDONNANCES_REQUEST =
  "PARTICULIER_GET_ORDONNANCES_REQUEST";
export const PARTICULIER_GET_ORDONNANCES_SUCCESS =
  "PARTICULIER_GET_ORDONNANCES_SUCCESS";
export const PARTICULIER_GET_ORDONNANCES_FAIL =
  "PARTICULIER_GET_ORDONNANCES_FAIL";

export const PARTICULIER_SAVE_RDV = "PARTICULIER_SAVE_RDV";
export const PARTICULIER_SAVE_RDV_RESET = "PARTICULIER_SAVE_RDV_RESET";

export const DONNEUR_SANG_SEARCH_REQUEST = "DONNEUR_SANG_SEARCH_REQUEST";
export const DONNEUR_SANG_SEARCH_SUCCESS = "DONNEUR_SANG_SEARCH_SUCCESS";
export const DONNEUR_SANG_SEARCH_FAIL = "DONNEUR_SANG_SEARCH_FAIL";
