export const USER_STATE = {
    GET_USER: "GET_USER",
    SET_USER: "SET_USER",
    GET_TOKEN: "GET_TOKEN",
    SET_TOKEN: "SET_TOKEN",
    SET_ROLE: "SET_ROLE",
    GET_ROLE: "GET_ROLE",
    SET_APPOINTMENTS: "SET_APPOINTMENTS",
    GET_APPOINTMENTS: "GET_APPOINTMENTS",
    SET_HOURS: "SET_HOURS",
    GET_HOURS: "GET_HOURS",
    REMOVE_USER: "REMOVE_USER",

  };